name: CI

on:
  push:
    branches: [main, dev, ci-*]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint:format
      - run: bun run lint
      - run: bun run test
